<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

 <ItemGroup>
    <PackageReference Include="MongoDB.EntityFrameworkCore" Version="10.0.2" />
  </ItemGroup>

 <ItemGroup>
   <ProjectReference Include="..\Claims.Data.Abstractions\Claims.Data.Abstractions.csproj" />
   <ProjectReference Include="..\Claims.Domain\Claims.Domain.csproj" />
 </ItemGroup>

</Project>
